---
title: Moon
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
bio: Minimal, one column jekyll theme.
description: Moon is a minimal, one column jekyll theme for your blog.
reading_time: true
words_per_minute: 200
logo: assets/img/logo.png
background: assets/img/placeholder-big.jpg
tiled_bg: false
locale: en_US
url: https://taylantatli.github.io/Moon
permalink: "/:title/"
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
mathjax: true
sass:
  sass_dir: _sass
  style: compressed
disqus_shortname: taylantatli
twitter: username
facebook: username
github-url: username
instagram: username
steam: username
gems:
- jekyll-mentions
- jekyll-feed
- jekyll-sitemap
- jekyll-gist
jekyll-mentions:
  base_url: https://github.com
exclude:
- README.md
- Gemfile
- Gemfile.lock
- node_modules
- gulpfile.js
- package.json
- _site
- src
- vendor
- CNAME
- LICENSE
- Rakefile
